### ISSUE TITLE
Integrate the topics model with KDL

### ISSUE THREAD

**Issue by IGZVasjaUrbancic** [konstellation-io/kdl-server#149]
- Assign topics to all assets using the latest candidate topic prediction model
- Leave a sufficient traceability to be able to inspect / change / update the topics model and associated predicted asset topics easily

**Comment by marcvivancos** [comment]
- [ ] Add topic assignment to the data pipeline.
- [ ] Add topic integration to gRPC server and App on kdl-server.
- [ ] Run pipeline and update prod datasets.
