### ISSUE TITLE
Implement IdP integration (LDAP) in KDL

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kdl-server#151]
- [x] Configure Gitea to use a LDAP provider
- [x] Try to connect with the IGZ JumpCloud to validate it
- [x] Review Gitea image, current image is based on a fork due to our integration of automate Oauth2 application tokens
- [x] Test the Gitea synchonization with an external idP (LDAP) with an interval of 10min

- [x] Remove the feature of add users from KDL UI
- [x] Remove the feature of delete users from KDL UI
- [x] Change user access level from user list (also remove the three dots control)
- [x] Add last synchronization timestamp and a button to force synchronization in user list
- [x] Add synchronization from kdl-server with gitea user database that run each 10min

More info: https://github.com/konstellation-io/kdl-server/discussions/274

**Comment by danielchg** [comment]
it is posible to automate the add authentication source in Gitea viea the CLI:

```gitea admin auth add-ldap --name ldap --security-protocol unencrypted --host mydomain.org --port 389 --user-search-base "ou=Users,dc=mydomain,dc=org" --user-filter "(&(objectClass=posixAccount)(uid=%s))" --email-attribute mail```
