### ISSUE TITLE
KDL User interface feedback:

### ISSUE THREAD

**Issue by jonasdacruz** [konstellation-io/kdl-server#153]
- The Start / Stop button at the bottom of the menu referring to the user tools does not understand what it does or its relationship with Jupyter and VSCode.
- The server options cannot be in the drop-down of the graphs, we have to look for a standard solution, it must have a very clear settings button at the server level.
-  When changing projects, it is necessary to notify if there are changes in Jupyter or VSCode without saving in the user tools to ensure that things not saved by mistake are not lost.

**Comment by mgs95** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/23691885/109797357-a6d5fb00-7c19-11eb-845c-317be2f22ead.png)
![image](https://user-images.githubusercontent.com/23691885/109797417-bb19f800-7c19-11eb-87d1-241921d8725e.png)

The idea is to make a block with the science toolkit tools, relate jupyter and vscode with the activable tools by using the status circle and the text ("USER TOOLS ARE RUNNING" | "USER TOOLS ARE STOPPED") and to locate the action button closer to the tools.

**Comment by mgs95** [comment]
Ideas for the second point:

![image (2)](https://user-images.githubusercontent.com/23691885/109833803-db5dad00-7c41-11eb-9e99-ce896048296b.png)
![image (3)](https://user-images.githubusercontent.com/23691885/109833970-021be380-7c42-11eb-82c1-e19b486058c1.png)
![image (4)](https://user-images.githubusercontent.com/23691885/109833989-06e09780-7c42-11eb-95d6-d305ff6473a5.png)
![image (5)](https://user-images.githubusercontent.com/23691885/109833997-08aa5b00-7c42-11eb-90c3-4656c3d2bd07.png)
![image (6)](https://user-images.githubusercontent.com/23691885/109834016-0d6f0f00-7c42-11eb-839d-e2a515348e9c.png)

**Comment by jonasdacruz** [comment]
> Something like this?
> ![image](https://user-images.githubusercontent.com/23691885/109797357-a6d5fb00-7c19-11eb-845c-317be2f22ead.png)
> ![image](https://user-images.githubusercontent.com/23691885/109821271-1954d400-7c36-11eb-9085-8c11f5b34e9b.png)
> 
> The idea is to make a block with the science toolkit tools, relate jupyter and vscode with the activable tools by using the status circle and the text ("USER TOOLS ARE RUNNING" | "USER TOOLS ARE STOPPED") and to locate the action button closer to the tools.

How does it look like when user tools are off?

**Comment by jonasdacruz** [comment]
> Ideas for the second point:
> 
> ![image (2)](https://user-images.githubusercontent.com/23691885/109833803-db5dad00-7c41-11eb-9e99-ce896048296b.png)
> ![image (3)](https://user-images.githubusercontent.com/23691885/109833970-021be380-7c42-11eb-82c1-e19b486058c1.png)
> ![image (4)](https://user-images.githubusercontent.com/23691885/109833989-06e09780-7c42-11eb-95d6-d305ff6473a5.png)
> ![image (5)](https://user-images.githubusercontent.com/23691885/109833997-08aa5b00-7c42-11eb-90c3-4656c3d2bd07.png)
> ![image (6)](https://user-images.githubusercontent.com/23691885/109834016-0d6f0f00-7c42-11eb-839d-e2a515348e9c.png)

I think the third one is the best one:

![image (4)](https://user-images.githubusercontent.com/23691885/109833989-06e09780-7c42-11eb-95d6-d305ff6473a5.png)

Maybe the second icon should be the more typical settings icon: 

![image](https://user-images.githubusercontent.com/754289/109836544-8c654700-7c44-11eb-89d0-51c048170c5a.png)

**Comment by IGZEnriqueRomera** [comment]
I think that such an icon is confusing when you are in a project screen, because you don't know if it's related to the server users or the project members

**Comment by IGZEnriqueRomera** [comment]
![image](https://user-images.githubusercontent.com/5045058/110934107-e2fe0f80-832d-11eb-882a-f0fe8ac9c0d2.png)
