### ISSUE TITLE
Show clone external repository errors in User Interface

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kdl-server#178]
When adding a new external repository, autocloning is done using your own ssh key, if the key located at kdl is not added to the external repo (you cannot access the repo using your own ssh key as it is not added at the target repo) you will not be able to clone the repo. We are not showing any errors when this happens. We should show this error to the user as he will not be able to work on the project.

**Comment by rrbarrero** [comment]
For fix this issue, it's necessary to communicate repoCLoner with the front. Perhaps, the better approach it's to use a broker and websocket service but we need to study anothers possibilities.
