### ISSUE TITLE
Test Authentication Source with an AD in Azure (like the Zara LDAP)

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kdl-server#313]

**Comment by danielchg** [comment]
https://blog.anoff.io/2019-03-23-configure-azure-ad-for-gitea/

**Comment by danielchg** [comment]
the method to integrate the authentacion of Gitea with both Azure AD via OpenID and Azure AD DS via LDAPS are documented in the following Github discursion https://github.com/konstellation-io/kdl-server/discussions/333
