### ISSUE TITLE
Add Logout feature

### ISSUE THREAD

**Issue by mgs95** [konstellation-io/kdl-server#410]
We want the user to be able to log out so signing with another account is easier.

As cookies are protected (HTTP Only), we need to perform the logout logic from the backend side.

**Comment by angelsanchez** [comment]
This is not possible.
We can close the session with the oauth2-proxy easily using the sing-out endpoint. But there is no way to close the session with the oAuth2 provider in our case Gitea. So we can only redirect to the oAuth2 provider but if the user doesn't logout manually from Gitea, he can re-login into kdl-server again returnin back.
More info:
- https://oauth2-proxy.github.io/oauth2-proxy/docs/7.0.x/features/endpoints/
