### ISSUE TITLE
Register SSH keys in Project creation

### ISSUE THREAD

**Issue by IGZEnriqueRomera** [konstellation-io/kdl-server#7]
Register Server SSH keys and Run git clone to make available the repo on Jupyter and VSCode context

- Store public key in gitea
- Store private and public key in MongoDB
- Create k8s secret with the private key and mount in the user home tools

SSH keys (both private and public) are accessible from Admin UI, queries should return these values. Also, the user can manually regenerate the keys to new generated ones.

**Comment by mgs95** [comment]
Related #30
