### ISSUE TITLE
Usernames that contains "_" characters cause some related K8s objects to fail on create

### ISSUE THREAD

**Issue by alejandrogr** [konstellation-io/kdl-server#850]
Resources in K8 created for users (like ServiceAccounts, Secrets...) are named taking in account the username. When a username has an "_" in its name, the "_" is translated to the k8s resources. K8s resources must adhere to the DNS Subdomain Spec (https://kubernetes.io/docs/concepts/overview/working-with-objects/names/) and the "_" is not valid.

This is causing users that contain "_" in their name to fail to be created and remain as zombie users inside the application since they are unusable.

**Comment by IGZmanuelMartinVivaldi** [comment]
Pending of Keycloak implementation. Mayke Keycloak don´t allow "_" or use email address, so this won´t happen
