### ISSUE TITLE
Allow UserTools to select capabilities when starting

### ISSUE THREAD

**Issue by alejandrogr** [konstellation-io/kdl-server#920]
UserTools must be limited to specific capabilities when starting up, so the users tools are limited to specific nodes inside a cluster.

```json
[{
"Id": "GPU_CAP",
"name": "GPU V100",
"default": true,
"nodeSelectors": {"gpu-type: v100"},
"affinities": [],
"tolerations": [
  "gpu": "true"
]
}]
```

**UI requirements:**

- [x]  Add a new capabilities selector on the navigation bar, on the right side of the runtimes selector.
- [x]  In case there are no capabilities do not show the selector, this won't allow the user to run the UserTools until a DevOps has added at least one capability.
- [x]  If there is only 1 capability configured do not show the selector and mark the capability as selected.
- [x] In case there is more than one capability configured, show the selector with all the available capabilities and force the user to select one before continuing. Define a field in the capabilities entity for allowing to define it as default, and select the default capability on the first load.
  - [x] In case there is more than one capability defined as default, select the first one in the order they are returned in the service
  - [x] Sort the capabilities to show the default ones first.
- [x] On the selected runtime details page, add a new label on the right of the current status label with the name of the selected capability.
- [x] Update cypress tests

**Backed requirements:**

- [x] Add the capabilities as a new collection on MongoDB
- [x] Add the GraphQL service to expose the capabilities as a new endpoint
- [x] Modify the GraphQL service to add the selected capability on the service responsible for creating the user tools.
- [x] Add the nodeSelector from the selected capability to the specs in case there is one selected
- [x] Add the selected capability ID as a label to the specs
- [x] Add a GraphQL service to expose the selected capability on a running pod by reading the label defined on the above point.

**Comment by dfinteligenz** [comment]
**UI requirements:**
- Add a new step after the selection of the runtime to select the capabilities
- In case there are no capabilities do not show the new step
- If there is only 1 capability configured do not show the new step and mark the capability as selected
- In case there is more than one capability configured, show the new step with all the available capabilities and force the user to select one before continuing.

**Backed requirements:**
- Add the capabilities as a new collection on MongoDB
- Add the GraphQL API to expose the capabilities as a new endpoint
- Modify the GraphQL API to add the selected capability on the service responsible for creating the user tools.
